# Backend configuration: Connects to your GitHub repository
# and uses your Cloudflare Worker for authentication.
    backend:
      name: github # Specifies the Git provider
      repo: baditaflorin/0deepresearch # Your GitHub repository path (username/repo_name)
      branch: main # Your default branch (e.g., main or master)

      # --- Sveltia Authenticator Configuration ---
      base_url: https://sveltia-cms-auth.baditaflorin.workers.dev

# Enable editorial workflow (optional, but common for a review process)
    publish_mode: editorial_workflow

# Media files will be stored in the 'static/uploads' directory of your repo.
    media_folder: "static/uploads"
# The public path for media files (relative to your site's root).
    public_folder: "/uploads"

# Define the content collections
    collections:
      - name: "pages"
        label: "Pages"
        folder: "content"
        create: true
        slug: "{{slug}}"
        format: toml # Front matter format
        extension: "md" # <--- ADD THIS LINE for file extension
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", picker_utc: false}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "posts"
        label: "Posts"
        folder: "content/posts"
        create: true
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # This generates the filename stem
        format: toml # Front matter format
        extension: "md" # <--- ADD THIS LINE for file extension
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", picker_utc: false}
          - {label: "Draft", name: "draft", widget: "boolean", default: true}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}

      - name: "utility_pages" # For specific files like _index.md
        label: "Utility Pages"
        files:
          - name: "about_content"
            label: "About Us Page Content"
            file: "content/about/_index.md" # This specifies the full filename, so extension field isn't usually needed here
            format: toml # Front matter format
            # extension: "md" # Typically not needed when 'file' path is absolute
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", picker_utc: false}
              - {label: "Draft", name: "draft", widget: "boolean", default: false}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Body", name: "body", widget: "markdown"}
          # If you add content/posts/_index.md here, it would look similar:
          # - name: "posts_index_content"
          #   label: "Posts List Page Content"
          #   file: "content/posts/_index.md"
          #   format: toml
          #   fields:
          #     - {label: "Title", name: "title", widget: "string"}
          #     - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}
          #     - {label: "Description", name: "description", widget: "text"}
          #     - {label: "Body", name: "body", widget: "markdown"}

# Global output settings (less common to need if format is per collection)
# output:
#   toml:
#     # Sveltia specific TOML output options if available
