# Backend configuration: Connects to your GitHub repository
# and uses your Cloudflare Worker for authentication.
backend:
  name: github # Specifies the Git provider
  repo: baditaflorin/0deepresearch # Your GitHub repository path (username/repo_name)
  branch: main # Your default branch (e.g., main or master)

  # --- Sveltia Authenticator Configuration ---
  base_url: https://sveltia-cms-auth.baditaflorin.workers.dev

# Enable editorial workflow (optional, but common for a review process)
publish_mode: editorial_workflow

# Media files will be stored in the 'static/uploads' directory of your repo.
media_folder: "static/uploads"
# The public path for media files (relative to your site's root).
public_folder: "/uploads"

# Define the content collections
collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    # format: yaml # YAML is often the default, can be explicit or omitted
    extension: "md" # Keep specifying .md extension
    fields:
      - {label: "Title", name: "title", widget: "string"}
      # YAML usually handles ISO dates well. Use standard datetime widget.
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    # format: yaml # YAML is often the default, can be explicit or omitted
    extension: "md" # Keep specifying .md extension
    fields:
      - {label: "Title", name: "title", widget: "string"}
      # YAML usually handles ISO dates well. Use standard datetime widget.
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "utility_pages" # For specific files like _index.md
    label: "Utility Pages"
    files:
      - name: "about_content"
        label: "About Us Page Content"
        file: "content/about/_index.md"
        # format: yaml # YAML is often the default, can be explicit or omitted
        # extension: "md" # Not needed when 'file' path is absolute
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Draft", name: "draft", widget: "boolean", default: false}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Body", name: "body", widget: "markdown"}
      # Example for posts/_index.md if managed here:
      # - name: "posts_index_content"
      #   label: "Posts List Page Content"
      #   file: "content/posts/_index.md"
      #   # format: yaml
      #   fields:
      #     - {label: "Title", name: "title", widget: "string"}
      #     - {label: "Date", name: "date", widget: "datetime"}
      #     - {label: "Description", name: "description", widget: "text"}
      #     - {label: "Body", name: "body", widget: "markdown"}

