# Backend configuration: Connects to your GitHub repository
backend:
  name: github # Use 'gitlab' or 'bitbucket' for other providers
  repo: baditaflorin/0deepresearch # Confirmed correct
  branch: main # Or your default branch, e.g., master
  site_domain: https://0deepresearch.com # Commented out for troubleshooting - often not needed for same-domain admin

# Enable editorial workflow. This creates pull requests for new content.
#publish_mode: editorial_workflow

# Media files will be stored in the 'static/uploads' directory of your repo.
# Make sure this path is accessible by your Hugo site.
media_folder: "static/uploads"
# The public path for media files (relative to your site's root).
public_folder: "/uploads"

# Define the content collections
collections:
  - name: "pages" # Used in routes, e.g., /admin/#/collections/pages
    label: "Pages" # Used in the UI
    folder: "content" # The path to the folder where page files are stored
    # filter: {field: "layout", value: "single"} # Optional: filter to only show files with layout: single. Consider if this is too restrictive.
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., "about-us" will create "content/about-us.md"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts"
    label: "Posts"
    folder: "content/posts" # Adjust if your posts are in a different directory
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Example: 2025-05-08-my-new-post.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Corrected structure for managing the "About Us" page (content/about/_index.md)
  # This is a 'files' collection, suitable for managing one or more specific files.
  - name: "utility_pages" # Changed name for clarity, can be anything unique
    label: "Utility Pages"
    files:
      - name: "about_content" # Unique identifier for this file entry
        label: "About Us Page Content"
        file: "content/about/_index.md" # Exact path to the file
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"} # Ensure this matches your front matter in _index.md
          - {label: "Draft", name: "draft", widget: "boolean", default: false} # Ensure this matches
          - {label: "Description", name: "description", widget: "string", required: false} # Ensure this matches
          - {label: "Body", name: "body", widget: "markdown"}
